site_name: cpuminer-remeowed Documentation
site_url: https://linuxmeow.github.io/cpuminer-remeowed-docs/
site_author: LinuxMeow
site_description: >-
  The complete documentation about the cpuminer-remeowed project.
  Documentation consists of source code documentation, build documentation and general info about the project.

repo_name: LinuxMeow/cpuminer-remeowed-docs
repo_url: https://github.com/LinuxMeow/cpuminer-remeowed-docs
edit_uri: ""

copyright: Copyright &copy; 2021 LinuxMeow

nav:
  - Home: index.md
  - What is cpuminer-remeowed: whatiscpuminerremeowed.md
  - Code: 
    - code.md
    - enable_donation: code/enable_donation.md
  - Build: build.md

theme:
  name: material

  language: en

  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
